artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/RohitPawar001/datasets/raw/refs/heads/main/zip_file2/bone_marrow.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  

data_validation:
  root_dir: artifacts/data_validation
  unzip_dir: artifacts\data_ingestion\csv_result-bone-marrow.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  